FirmwareUpdate|canLoader-console: fix undefined references of libembobj.so
The error triggered was:
libembobj.so.4.0.7: undefined reference to `feat_yarp_time_now'
libembobj.so.4.0.7: undefined reference to `ace_mutex_new'
libembobj.so.4.0.7: undefined reference to `ace_mutex_take'
libembobj.so.4.0.7: undefined reference to `ace_mutex_release'

The signature of these functions are defined in icub-firmware-shared as extern
And the implementation is in `embObjLib/FeatureInterface.cpp`